## Cloud deployment ##
networks:
  external:
    name: external
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${CLOUD_EXTERNAL_SUBNET:?Add to your env file}"
          gateway: "${CLOUD_EXTERNAL_GATEWAY:?Add to your env file}"
  authentik:
    name: authentik
    driver: bridge

services:
###########################################################################
# TRAEFIK (Reverse Proxy & SSL/TLS)
###########################################################################
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    networks:
      - external
    ports:
      - "80:80"
      - "443:443"
      - "${TRAEFIK_DASHBOARD_PORT:-8080}:8080"
    environment:
      - TZ=${TIMEZONE:?err}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${FOLDER_FOR_DATA:?err}/traefik/traefik.yaml:/traefik.yaml:ro
      - ${FOLDER_FOR_DATA:?err}/traefik/config.yaml:/config.yaml:ro
      - ${FOLDER_FOR_DATA:?err}/traefik/acme.json:/acme.json
    labels:
      - "tsdproxy.enable=false"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

###########################################################################
# AUTHENTIK (Upstream-Variante)
###########################################################################
  postgresql:
    image: docker.io/library/postgres:latest
    container_name: postgresql-authentik
    restart: unless-stopped
    networks:
      - authentik
    ports:
      - ${POSTGRESQL_PORT:-5432}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    labels:
      - "tsdproxy.enable=false"
    volumes:
      - ${FOLDER_FOR_DATA:?err}/postgresql:/var/lib/postgresql
    environment:
      - TZ=${TIMEZONE:?err}
      - POSTGRES_DB=${AUTHENTIK_DATABASE:?err}
      - POSTGRES_USER=${POSTGRESQL_USERNAME:?err}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD:?err}

  valkey:
    image: valkey/valkey:alpine
    container_name: valkey
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    networks:
      - authentik
    ports:
      - ${VALKEY_PORT:-6379}:6379
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    labels:
      - "tsdproxy.enable=false"
    volumes:
      - ${FOLDER_FOR_DATA:?err}/valkey:/data

  authentik:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_VERSION:-latest}
    container_name: authentik
    restart: unless-stopped
    user: ${PUID:?err}:${PGID:?err}
    networks:
      - authentik
      - external
    command: server
    environment:
      - TZ=${TIMEZONE:?err}
      - AUTHENTIK_LOG_LEVEL=info
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY:?err}
      - AUTHENTIK_REDIS__HOST=valkey
      - AUTHENTIK_POSTGRESQL__HOST=postgresql
      - AUTHENTIK_POSTGRESQL__NAME=${AUTHENTIK_DATABASE:-authentik}
      - AUTHENTIK_POSTGRESQL__USER=${POSTGRESQL_USERNAME:-authentik}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${POSTGRESQL_PASSWORD:?Postgres password is required}
      - AUTHENTIK_ERROR_REPORTING__ENABLED=${AUTHENTIK_ERROR_REPORTING__ENABLED:-false}
    volumes:
      - ${FOLDER_FOR_DATA:?err}/authentik/media:/media
      - ${FOLDER_FOR_DATA:?err}/authentik/templates:/templates
    ports:
      - ${WEBUI_PORT_AUTHENTIK:-9000}:9000
      - ${COMPOSE_PORT_HTTPS:-9443}:9443
    labels:
      - "tsdproxy.enable=true"
      - "tsdproxy.name=authentik"
      - "traefik.enable=true"
      - "traefik.http.routers.authentik.rule=Host(`${AUTHENTIK_DOMAIN}`)"
      - "traefik.http.routers.authentik.entrypoints=websecure"
      - "traefik.http.routers.authentik.tls.certresolver=letsencrypt"
      - "traefik.http.services.authentik.loadbalancer.server.port=9000"
    depends_on:
      postgresql:
        condition: service_healthy
      valkey:
        condition: service_healthy

  authentik-worker:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_VERSION:?err}
    container_name: authentik-worker
    restart: unless-stopped
    user: ${PUID:?err}:${PGID:?err}
    networks:
      - authentik
      - external
    command: worker
    environment:
      - TZ=${TIMEZONE:?err}
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY:?err}
      - AUTHENTIK_REDIS__HOST=valkey
      - AUTHENTIK_POSTGRESQL__HOST=postgresql
      - AUTHENTIK_POSTGRESQL__NAME=${AUTHENTIK_DATABASE:?err}
      - AUTHENTIK_POSTGRESQL__USER=${POSTGRESQL_USERNAME:?err}
      - AUTHENTIK_POSTGRESQL__PASSWORD=${POSTGRESQL_PASSWORD:?err}
      - AUTHENTIK_ERROR_REPORTING__ENABLED=${AUTHENTIK_ERROR_REPORTING__ENABLED:-false}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${FOLDER_FOR_DATA:?err}/certs:/certs
      - ${FOLDER_FOR_DATA:?err}/authentik/media:/media
      - ${FOLDER_FOR_DATA:?err}/authentik/templates:/templates
    depends_on:
      postgresql:
        condition: service_healthy
      valkey:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "ps -ef | grep worker | grep -v grep"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s


###########################################################################
# MEDIA (Cloud)
###########################################################################
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    user: ${PUID:?err}:${PGID:?err}
    networks:
      - external
    environment:
      - TZ=${TIMEZONE:?err}
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
    volumes:
      - ${FOLDER_FOR_DATA:?err}/jellyfin:/config
      - ${FOLDER_FOR_MEDIA:?err}:/media
    ports:
      - ${WEBUI_PORT_JELLYFIN:-8096}:8096
    labels:
      - "tsdproxy.enable=true"
      - "tsdproxy.name=jellyfin"
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_DOMAIN}`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls.certresolver=letsencrypt"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    networks:
      - external
    environment:
      - TZ=${TIMEZONE:?err}
      - PLEX_CLAIM=${PLEX_CLAIM:-}
    volumes:
      - ${FOLDER_FOR_DATA:?err}/plex:/config
      - ${FOLDER_FOR_MEDIA:?err}:/media
    ports:
      - ${WEBUI_PORT_PLEX:-32400}:32400
    labels:
      - "tsdproxy.enable=true"
      - "tsdproxy.name=plex"
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`${PLEX_DOMAIN}`)"
      - "traefik.http.routers.plex.entrypoints=websecure"
      - "traefik.http.routers.plex.tls.certresolver=letsencrypt"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"


###########################################################################
# WATCHTOWER (Container Auto-Update)
###########################################################################
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    networks:
      - external
    user: ${PUID:?err}:${PGID:?err}
    labels:
      - "tsdproxy.enable=true"
      - "tsdproxy.name=watchtower"
    environment:
      - TZ=${TIMEZONE:?err}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=false
      - WATCHTOWER_POLL_INTERVAL=3600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


      
############################################################################
# TSD Proxy # https://almeidapaulopt.github.io
############################################################################

  tsdproxy:
    image: almeidapaulopt/tsdproxy:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - datadir:/data
      - ${FOLDER_FOR_DATA:?err}/tsdproxy_hetzner:/config
    restart: unless-stopped
    networks:
      - external
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTH_KEY:?TAILSCALE_AUTH_KEY missing}
    ports:
      - "80:8080"


volumes:
  # TSD Proxy Data
  datadir: